# Affected Tests Workflow
# Runs only tests affected by changes in the PR
# Dramatically reduces CI time for large test suites
#
# Usage: Copy to .github/workflows/affected-tests.yml

name: Affected Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write

jobs:
  determine-tests:
    name: Determine Affected Tests
    runs-on: ubuntu-latest
    outputs:
      has_tests: ${{ steps.affected.outputs.has_tests }}
      test_command: ${{ steps.affected.outputs.test_command }}
      test_files: ${{ steps.affected.outputs.test_files }}
      strategy: ${{ steps.affected.outputs.strategy }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CKB
        run: npm install -g @tastehub/ckb

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: .ckb/
          key: ckb-${{ runner.os }}-${{ hashFiles('**/*.go', '**/*.ts', '**/*.py') }}
          restore-keys: |
            ckb-${{ runner.os }}-

      - name: Initialize and Index
        run: |
          ckb init
          ckb index --if-stale=24h

      - name: Get Affected Tests
        id: affected
        run: |
          # Get affected tests using multiple strategies
          RANGE="${{ github.event.pull_request.base.sha }}..${{ github.sha }}"

          # Try coverage-based first (most accurate)
          RESULT=$(ckb affected-tests --range="$RANGE" --strategy=coverage --format=json 2>/dev/null || echo '{"tests":[],"strategy":"none"}')

          STRATEGY=$(echo "$RESULT" | jq -r '.strategy // "none"')
          TEST_COUNT=$(echo "$RESULT" | jq -r '.tests | length')

          if [ "$TEST_COUNT" -eq 0 ]; then
            # Fallback to import-based
            RESULT=$(ckb affected-tests --range="$RANGE" --strategy=imports --format=json 2>/dev/null || echo '{"tests":[],"strategy":"none"}')
            STRATEGY=$(echo "$RESULT" | jq -r '.strategy // "none"')
            TEST_COUNT=$(echo "$RESULT" | jq -r '.tests | length')
          fi

          if [ "$TEST_COUNT" -eq 0 ]; then
            # Final fallback to naming convention
            RESULT=$(ckb affected-tests --range="$RANGE" --strategy=naming --format=json 2>/dev/null || echo '{"tests":[],"strategy":"none"}')
            STRATEGY=$(echo "$RESULT" | jq -r '.strategy // "none"')
            TEST_COUNT=$(echo "$RESULT" | jq -r '.tests | length')
          fi

          echo "strategy=$STRATEGY" >> $GITHUB_OUTPUT

          if [ "$TEST_COUNT" -gt 0 ]; then
            echo "has_tests=true" >> $GITHUB_OUTPUT

            # Get runnable command
            CMD=$(ckb affected-tests --range="$RANGE" --strategy="$STRATEGY" --output=command 2>/dev/null || echo "")
            echo "test_command=$CMD" >> $GITHUB_OUTPUT

            # Get test file list for display
            FILES=$(echo "$RESULT" | jq -r '.tests | join(",")')
            echo "test_files=$FILES" >> $GITHUB_OUTPUT
          else
            echo "has_tests=false" >> $GITHUB_OUTPUT
            echo "test_command=" >> $GITHUB_OUTPUT
            echo "test_files=" >> $GITHUB_OUTPUT
          fi

          # Save full result for reporting
          echo "$RESULT" > affected-tests.json

      - name: Upload Analysis
        uses: actions/upload-artifact@v4
        with:
          name: affected-tests-analysis
          path: affected-tests.json
          retention-days: 7

  run-go-tests:
    name: Run Go Tests
    needs: determine-tests
    if: needs.determine-tests.outputs.has_tests == 'true' && contains(needs.determine-tests.outputs.test_files, '_test.go')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run Affected Tests
        run: |
          CMD="${{ needs.determine-tests.outputs.test_command }}"
          if [ -n "$CMD" ]; then
            echo "Running: $CMD"
            eval "$CMD"
          fi

  run-js-tests:
    name: Run JavaScript/TypeScript Tests
    needs: determine-tests
    if: needs.determine-tests.outputs.has_tests == 'true' && (contains(needs.determine-tests.outputs.test_files, '.test.ts') || contains(needs.determine-tests.outputs.test_files, '.test.js') || contains(needs.determine-tests.outputs.test_files, '.spec.ts'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Affected Tests
        run: |
          # Parse test files and run with Jest/Vitest
          FILES="${{ needs.determine-tests.outputs.test_files }}"
          if [ -n "$FILES" ]; then
            # Convert comma-separated to space-separated
            TEST_FILES=$(echo "$FILES" | tr ',' ' ')
            npx jest $TEST_FILES --passWithNoTests || npx vitest run $TEST_FILES
          fi

  run-python-tests:
    name: Run Python Tests
    needs: determine-tests
    if: needs.determine-tests.outputs.has_tests == 'true' && contains(needs.determine-tests.outputs.test_files, 'test_')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install pytest pytest-cov
          pip install -r requirements.txt || true

      - name: Run Affected Tests
        run: |
          FILES="${{ needs.determine-tests.outputs.test_files }}"
          if [ -n "$FILES" ]; then
            # Convert comma-separated to space-separated
            TEST_FILES=$(echo "$FILES" | tr ',' ' ')
            pytest $TEST_FILES -v
          fi

  no-tests:
    name: No Tests Affected
    needs: determine-tests
    if: needs.determine-tests.outputs.has_tests == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Report
        run: |
          echo "No tests were identified as affected by this change."
          echo "Strategy used: ${{ needs.determine-tests.outputs.strategy }}"

          echo "## No Affected Tests" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "No tests were identified as affected by this change." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "This could mean:" >> $GITHUB_STEP_SUMMARY
          echo "- Changes don't affect tested code paths" >> $GITHUB_STEP_SUMMARY
          echo "- No coverage data available for precise mapping" >> $GITHUB_STEP_SUMMARY
          echo "- Files changed don't have corresponding tests" >> $GITHUB_STEP_SUMMARY

  summary:
    name: Test Summary
    needs: [determine-tests, run-go-tests, run-js-tests, run-python-tests, no-tests]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Create Summary
        uses: actions/github-script@v7
        with:
          script: |
            const hasTests = '${{ needs.determine-tests.outputs.has_tests }}' === 'true';
            const strategy = '${{ needs.determine-tests.outputs.strategy }}';
            const files = '${{ needs.determine-tests.outputs.test_files }}';

            let summary = '## Affected Tests Summary\n\n';

            if (hasTests) {
              const testList = files.split(',').filter(f => f);
              summary += `**Strategy:** ${strategy}\n`;
              summary += `**Tests run:** ${testList.length}\n\n`;
              summary += '<details>\n<summary>Test files</summary>\n\n';
              testList.forEach(f => {
                summary += `- \`${f}\`\n`;
              });
              summary += '\n</details>';
            } else {
              summary += 'No tests affected by this change.';
            }

            core.summary.addRaw(summary).write();
