# CODEOWNERS Sync Workflow
# Detects ownership drift and creates PRs to update CODEOWNERS
#
# Usage: Copy to .github/workflows/codeowners-sync.yml

name: CODEOWNERS Sync

on:
  schedule:
    # Run weekly on Sundays at 4 AM UTC
    - cron: '0 4 * * 0'
  workflow_dispatch:
    inputs:
      threshold:
        description: 'Drift threshold (0.0-1.0, lower = more sensitive)'
        required: false
        default: '0.4'
      dry_run:
        description: 'Dry run (no PR created)'
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    name: Sync CODEOWNERS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CKB
        run: npm install -g @tastehub/ckb

      - name: Initialize and Index
        run: |
          ckb init
          ckb index

      - name: Check Ownership Drift
        id: drift
        run: |
          THRESHOLD="${{ github.event.inputs.threshold || '0.4' }}"

          # Get drift analysis
          ckb ownership drift \
            --threshold="$THRESHOLD" \
            --format=json \
            > drift.json

          # Count files with drift
          DRIFT_COUNT=$(jq -r '.summary.filesWithDrift // 0' drift.json)
          SIGNIFICANT=$(jq -r '[.files[] | select(.actualOwner != .declaredOwner)] | length' drift.json)

          echo "drift_count=$DRIFT_COUNT" >> $GITHUB_OUTPUT
          echo "significant=$SIGNIFICANT" >> $GITHUB_OUTPUT

          # Check if CODEOWNERS exists
          if [ -f "CODEOWNERS" ] || [ -f ".github/CODEOWNERS" ] || [ -f "docs/CODEOWNERS" ]; then
            echo "has_codeowners=true" >> $GITHUB_OUTPUT
          else
            echo "has_codeowners=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate Updated CODEOWNERS
        if: steps.drift.outputs.significant > 0
        id: generate
        run: |
          # Determine CODEOWNERS location
          if [ -f ".github/CODEOWNERS" ]; then
            CODEOWNERS_PATH=".github/CODEOWNERS"
          elif [ -f "docs/CODEOWNERS" ]; then
            CODEOWNERS_PATH="docs/CODEOWNERS"
          else
            CODEOWNERS_PATH="CODEOWNERS"
          fi

          echo "path=$CODEOWNERS_PATH" >> $GITHUB_OUTPUT

          # Generate suggested CODEOWNERS
          ckb ownership suggest \
            --format=codeowners \
            > suggested-codeowners.txt

          # Create a merged version (preserving comments and adding suggestions)
          if [ -f "$CODEOWNERS_PATH" ]; then
            # Keep header comments from original
            grep '^#' "$CODEOWNERS_PATH" > new-codeowners.txt || true
            echo "" >> new-codeowners.txt
            echo "# Auto-generated ownership rules (updated $(date -u +%Y-%m-%d))" >> new-codeowners.txt
            echo "" >> new-codeowners.txt

            # Add suggested rules
            cat suggested-codeowners.txt >> new-codeowners.txt
          else
            # Create new CODEOWNERS
            cat > new-codeowners.txt << 'EOF'
          # CODEOWNERS file
          # Auto-generated by CKB based on git commit history
          #
          # Each line is a file pattern followed by one or more owners.
          # Order matters: later patterns take precedence.

          EOF
            cat suggested-codeowners.txt >> new-codeowners.txt
          fi

      - name: Generate Drift Report
        if: steps.drift.outputs.drift_count > 0
        run: |
          cat > drift-report.md << 'EOF'
          # Ownership Drift Report

          This PR updates CODEOWNERS based on actual commit history.

          ## Summary

          EOF

          echo "- **Files with ownership drift:** ${{ steps.drift.outputs.drift_count }}" >> drift-report.md
          echo "- **Significant changes:** ${{ steps.drift.outputs.significant }}" >> drift-report.md
          echo "" >> drift-report.md

          echo "## Changes" >> drift-report.md
          echo "" >> drift-report.md
          echo "| Path | Declared Owner | Actual Owner | Confidence |" >> drift-report.md
          echo "|------|----------------|--------------|------------|" >> drift-report.md

          jq -r '.files[] | select(.actualOwner != .declaredOwner) | "| `\(.path)` | \(.declaredOwner // "none") | \(.actualOwner) | \(.confidence * 100 | floor)% |"' drift.json \
            | head -20 >> drift-report.md

          MORE=$(jq -r '[.files[] | select(.actualOwner != .declaredOwner)] | length' drift.json)
          if [ "$MORE" -gt 20 ]; then
            echo "" >> drift-report.md
            echo "*...and $((MORE - 20)) more files*" >> drift-report.md
          fi

          echo "" >> drift-report.md
          echo "---" >> drift-report.md
          echo "*Generated by CKB ownership analysis*" >> drift-report.md

      - name: Create Pull Request
        if: steps.drift.outputs.significant > 0 && github.event.inputs.dry_run != 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: sync CODEOWNERS with actual ownership"
          title: "[CKB] Update CODEOWNERS based on commit history"
          body-path: drift-report.md
          branch: ckb/codeowners-sync
          delete-branch: true
          labels: |
            automated
            codeowners
          reviewers: |
            ${{ github.repository_owner }}

      - name: Dry Run Summary
        if: github.event.inputs.dry_run == 'true'
        run: |
          echo "## Dry Run Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Files with drift:** ${{ steps.drift.outputs.drift_count }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Suggested CODEOWNERS" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat suggested-codeowners.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Upload Analysis
        uses: actions/upload-artifact@v4
        with:
          name: ownership-analysis
          path: |
            drift.json
            suggested-codeowners.txt
            drift-report.md
          retention-days: 30

      - name: Summary
        run: |
          echo "## CODEOWNERS Sync Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Files analyzed for drift:** All" >> $GITHUB_STEP_SUMMARY
          echo "- **Files with ownership drift:** ${{ steps.drift.outputs.drift_count }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Significant ownership changes:** ${{ steps.drift.outputs.significant }}" >> $GITHUB_STEP_SUMMARY
