# Contract-Aware CI Workflow
# Detects changes to API contracts (protobuf, OpenAPI) and warns about cross-boundary impact
#
# Usage: Copy to .github/workflows/contract-check.yml

name: Contract Safety Check

on:
  pull_request:
    paths:
      - '**/*.proto'
      - '**/openapi*.yaml'
      - '**/openapi*.json'
      - '**/swagger*.yaml'
      - '**/swagger*.json'
      - 'api/**'
      - 'proto/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  check-contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CKB
        run: npm install -g @tastehub/ckb

      - name: Initialize
        run: |
          ckb init
          ckb serve --port 8080 &
          sleep 2

      - name: Find Changed Contracts
        id: contracts
        run: |
          CONTRACTS=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.sha }} \
            | grep -E '\.(proto|yaml|json)$' \
            | grep -E '(proto/|openapi/|api/|swagger)' || true)

          if [ -n "$CONTRACTS" ]; then
            echo "found=true" >> $GITHUB_OUTPUT
            echo "$CONTRACTS" > changed-contracts.txt
            echo "count=$(echo "$CONTRACTS" | wc -l | tr -d ' ')" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
            echo "count=0" >> $GITHUB_OUTPUT
          fi

      - name: Analyze Contract Impact
        if: steps.contracts.outputs.found == 'true'
        id: impact
        run: |
          HIGH_RISK=0

          cat > contract-report.md << 'EOF'
          ## Contract Change Analysis

          This PR modifies API contract files. Cross-boundary impact analysis:

          EOF

          while IFS= read -r CONTRACT; do
            echo "Analyzing: $CONTRACT"

            RESULT=$(curl -s "http://localhost:8080/contracts/impact?path=$CONTRACT" || echo '{}')

            VISIBILITY=$(echo "$RESULT" | jq -r '.visibility // "unknown"')
            CONSUMERS=$(echo "$RESULT" | jq -r '.consumers | length // 0')
            RISK=$(echo "$RESULT" | jq -r '.riskLevel // "unknown"')

            echo "" >> contract-report.md
            echo "### \`$CONTRACT\`" >> contract-report.md
            echo "" >> contract-report.md
            echo "- **Visibility:** $VISIBILITY" >> contract-report.md
            echo "- **Known consumers:** $CONSUMERS" >> contract-report.md
            echo "- **Risk level:** $RISK" >> contract-report.md

            if [ "$CONSUMERS" -gt 0 ]; then
              echo "" >> contract-report.md
              echo "**Consumers:**" >> contract-report.md
              echo "$RESULT" | jq -r '.consumers[] | "- \(.repo) (\(.confidence) confidence)"' >> contract-report.md
            fi

            FACTORS=$(echo "$RESULT" | jq -r '.riskFactors // []')
            if [ "$FACTORS" != "[]" ]; then
              echo "" >> contract-report.md
              echo "**Risk factors:**" >> contract-report.md
              echo "$RESULT" | jq -r '.riskFactors[] | "- \(.)"' >> contract-report.md
            fi

            if [ "$RISK" = "high" ] || [ "$RISK" = "critical" ]; then
              HIGH_RISK=$((HIGH_RISK + 1))
            fi

          done < changed-contracts.txt

          echo "" >> contract-report.md
          echo "---" >> contract-report.md
          echo "*Generated by CKB contract analysis*" >> contract-report.md

          echo "high_risk=$HIGH_RISK" >> $GITHUB_OUTPUT

      - name: Post Contract Report
        if: steps.contracts.outputs.found == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: contract-analysis
          path: contract-report.md

      - name: Generate Refactor Checklist
        if: steps.impact.outputs.high_risk > 0
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const contracts = fs.readFileSync('changed-contracts.txt', 'utf8').trim().split('\n');

            let checklist = `## ⚠️ Contract Change Checklist\n\n`;
            checklist += `This PR modifies ${contracts.length} contract file(s) with potential cross-boundary impact.\n\n`;
            checklist += `### Before Merge\n\n`;
            checklist += `- [ ] Verified backward compatibility\n`;
            checklist += `- [ ] Notified downstream consumers\n`;
            checklist += `- [ ] Updated version numbers if breaking\n`;
            checklist += `- [ ] Added deprecation notices for removed fields\n`;
            checklist += `- [ ] Updated client SDKs if applicable\n`;
            checklist += `\n### Contract Files\n\n`;

            contracts.forEach(c => {
              checklist += `- [ ] Reviewed \`${c}\`\n`;
            });

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: checklist
            });

      - name: Fail on High Risk
        if: steps.impact.outputs.high_risk > 0
        run: |
          echo "::error::${{ steps.impact.outputs.high_risk }} contract(s) have high-risk changes affecting consumers"
          echo "Review the contract analysis and ensure downstream teams are notified."
          exit 1
