# Dead Code Detection Workflow
# Runs weekly to identify potentially unused code
#
# Usage: Copy to .github/workflows/dead-code-detection.yml

name: Dead Code Detection

on:
  schedule:
    # Run weekly on Mondays at 3 AM UTC
    - cron: '0 3 * * 1'
  workflow_dispatch:
    inputs:
      threshold:
        description: 'Confidence threshold (0.0-1.0)'
        required: false
        default: '0.9'
      limit:
        description: 'Maximum results to report'
        required: false
        default: '50'

permissions:
  contents: read
  issues: write

jobs:
  detect:
    name: Detect Dead Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CKB
        run: npm install -g @tastehub/ckb

      - name: Initialize and Index
        run: |
          ckb init
          ckb index

      - name: Detect Dead Code
        id: dead-code
        run: |
          THRESHOLD="${{ github.event.inputs.threshold || '0.9' }}"
          LIMIT="${{ github.event.inputs.limit || '50' }}"

          # Get dead code candidates as JSON
          ckb dead-code \
            --threshold="$THRESHOLD" \
            --limit="$LIMIT" \
            --format=json \
            > dead-code.json

          # Extract summary stats
          TOTAL=$(jq -r '.summary.totalCandidates // 0' dead-code.json)
          HIGH_CONF=$(jq -r '[.candidates[] | select(.confidence >= 0.95)] | length' dead-code.json)

          echo "total=$TOTAL" >> $GITHUB_OUTPUT
          echo "high_confidence=$HIGH_CONF" >> $GITHUB_OUTPUT

      - name: Generate Report
        run: |
          cat > dead-code-report.md << 'EOF'
          # Dead Code Detection Report

          **Run Date:** $(date -u +%Y-%m-%d)
          **Threshold:** ${{ github.event.inputs.threshold || '0.9' }}

          ## Summary

          EOF

          TOTAL=$(jq -r '.summary.totalCandidates // 0' dead-code.json)
          echo "- **Total candidates found:** $TOTAL" >> dead-code-report.md
          echo "" >> dead-code-report.md

          if [ "$TOTAL" -gt 0 ]; then
            echo "## High Confidence Candidates (>95%)" >> dead-code-report.md
            echo "" >> dead-code-report.md
            echo "| File | Symbol | Type | Confidence |" >> dead-code-report.md
            echo "|------|--------|------|------------|" >> dead-code-report.md

            jq -r '.candidates[] | select(.confidence >= 0.95) | "| `\(.file)` | \(.symbol) | \(.type) | \(.confidence * 100 | floor)% |"' dead-code.json >> dead-code-report.md

            echo "" >> dead-code-report.md
            echo "## Medium Confidence Candidates (90-95%)" >> dead-code-report.md
            echo "" >> dead-code-report.md
            echo "| File | Symbol | Type | Confidence |" >> dead-code-report.md
            echo "|------|--------|------|------------|" >> dead-code-report.md

            jq -r '.candidates[] | select(.confidence >= 0.90 and .confidence < 0.95) | "| `\(.file)` | \(.symbol) | \(.type) | \(.confidence * 100 | floor)% |"' dead-code.json >> dead-code-report.md
          else
            echo "*No dead code candidates found above threshold.*" >> dead-code-report.md
          fi

          echo "" >> dead-code-report.md
          echo "---" >> dead-code-report.md
          echo "*Generated by CKB*" >> dead-code-report.md

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: dead-code-report
          path: |
            dead-code.json
            dead-code-report.md
          retention-days: 90

      - name: Create Issue if Significant Dead Code Found
        if: steps.dead-code.outputs.high_confidence > 10
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('dead-code-report.md', 'utf8');
            const total = ${{ steps.dead-code.outputs.total }};
            const highConf = ${{ steps.dead-code.outputs.high_confidence }};

            // Check for existing open issue
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['dead-code', 'automated'],
              state: 'open'
            });

            const title = `[CKB] Dead Code Detected: ${highConf} high-confidence candidates`;

            if (issues.data.length > 0) {
              // Update existing issue
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issues.data[0].number,
                body: report
              });
            } else {
              // Create new issue
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: report,
                labels: ['dead-code', 'automated', 'tech-debt']
              });
            }

      - name: Summary
        run: |
          echo "## Dead Code Detection Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Total candidates:** ${{ steps.dead-code.outputs.total }}" >> $GITHUB_STEP_SUMMARY
          echo "- **High confidence (>95%):** ${{ steps.dead-code.outputs.high_confidence }}" >> $GITHUB_STEP_SUMMARY
