# Documentation Quality Workflow
# Enforces documentation coverage and detects stale symbol references
#
# Usage: Copy to .github/workflows/doc-quality.yml

name: Documentation Quality

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.go'
      - '**/*.ts'
      - '**/*.py'

permissions:
  contents: read
  pull-requests: write

env:
  COVERAGE_THRESHOLD: 70

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CKB
        run: npm install -g @tastehub/ckb

      - name: Initialize
        run: |
          ckb init
          ckb index
          ckb docs index

      - name: Check Coverage
        id: coverage
        run: |
          RESULT=$(ckb docs coverage --format=json)
          COVERAGE=$(echo "$RESULT" | jq -r '.coverage // 0')

          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT

          if (( $(echo "$COVERAGE < $COVERAGE_THRESHOLD" | bc -l) )); then
            echo "below_threshold=true" >> $GITHUB_OUTPUT
          else
            echo "below_threshold=false" >> $GITHUB_OUTPUT
          fi

      - name: Check Staleness
        id: staleness
        run: |
          RESULT=$(ckb docs stale --all --format=json)
          STALE=$(echo "$RESULT" | jq -r '.totalStale // 0')

          echo "stale_count=$STALE" >> $GITHUB_OUTPUT

          if [ "$STALE" -gt 0 ]; then
            echo "$RESULT" > stale-docs.json
          fi

      - name: Generate Report
        run: |
          cat > doc-report.md << 'EOF'
          ## Documentation Quality Report

          EOF

          COVERAGE=${{ steps.coverage.outputs.coverage }}
          STALE=${{ steps.staleness.outputs.stale_count }}
          THRESHOLD=$COVERAGE_THRESHOLD

          if (( $(echo "$COVERAGE >= $THRESHOLD" | bc -l) )); then
            echo "### ✅ Coverage: ${COVERAGE}% (threshold: ${THRESHOLD}%)" >> doc-report.md
          else
            echo "### ❌ Coverage: ${COVERAGE}% (below threshold: ${THRESHOLD}%)" >> doc-report.md
          fi

          echo "" >> doc-report.md

          if [ "$STALE" -gt 0 ]; then
            echo "### ⚠️ Stale References: $STALE" >> doc-report.md
            echo "" >> doc-report.md
            echo "The following documentation references symbols that may have changed:" >> doc-report.md
            echo "" >> doc-report.md

            if [ -f stale-docs.json ]; then
              jq -r '.reports[] | .stale[] | "- `\(.docPath):\(.line)`: \(.rawText) (\(.reason))"' stale-docs.json >> doc-report.md
            fi
          else
            echo "### ✅ No Stale References" >> doc-report.md
          fi

          echo "" >> doc-report.md
          echo "---" >> doc-report.md
          echo "*Generated by CKB documentation analysis*" >> doc-report.md

      - name: Post PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: doc-quality
          path: doc-report.md

      - name: Fail on Coverage
        if: steps.coverage.outputs.below_threshold == 'true'
        run: |
          echo "::error::Documentation coverage ${{ steps.coverage.outputs.coverage }}% is below threshold $COVERAGE_THRESHOLD%"
          exit 1

      - name: Warn on Staleness
        if: steps.staleness.outputs.stale_count > 0
        run: |
          echo "::warning::Found ${{ steps.staleness.outputs.stale_count }} stale documentation references"
