# Hotspot Monitor Workflow
# Tracks code hotspots over time and alerts on degradation
#
# Usage: Copy to .github/workflows/hotspot-monitor.yml

name: Hotspot Monitor

on:
  schedule:
    # Run daily at 5 AM UTC
    - cron: '0 5 * * *'
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  analyze-hotspots:
    name: Analyze Hotspots
    runs-on: ubuntu-latest
    outputs:
      new_hotspots: ${{ steps.compare.outputs.new_hotspots }}
      worsened: ${{ steps.compare.outputs.worsened }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CKB
        run: npm install -g @tastehub/ckb

      - name: Initialize
        run: |
          ckb init
          ckb index

      - name: Get Current Hotspots
        run: |
          ckb hotspots \
            --limit=50 \
            --format=json \
            > current-hotspots.json

          # Also get complexity-weighted hotspots
          ckb audit \
            --min-score=50 \
            --limit=30 \
            --format=json \
            > audit-results.json

      - name: Download Previous Baseline
        uses: dawidd6/action-download-artifact@v3
        continue-on-error: true
        with:
          workflow: hotspot-monitor.yml
          name: hotspot-baseline
          path: baseline/

      - name: Compare Hotspots
        id: compare
        run: |
          NEW_HOTSPOTS=0
          WORSENED=0

          if [ -f "baseline/hotspots.json" ]; then
            # Compare current to baseline
            # Find files that are new hotspots or have worsened
            jq -r '.hotspots[].filePath' current-hotspots.json | sort > current-files.txt
            jq -r '.hotspots[].filePath' baseline/hotspots.json | sort > baseline-files.txt

            # New hotspots (in current but not baseline)
            NEW_HOTSPOTS=$(comm -23 current-files.txt baseline-files.txt | wc -l | tr -d ' ')

            # Check for worsened scores
            while IFS= read -r file; do
              CURRENT_SCORE=$(jq -r --arg f "$file" '.hotspots[] | select(.filePath == $f) | .ranking.score // 0' current-hotspots.json)
              BASELINE_SCORE=$(jq -r --arg f "$file" '.hotspots[] | select(.filePath == $f) | .ranking.score // 0' baseline/hotspots.json)

              if [ -n "$CURRENT_SCORE" ] && [ -n "$BASELINE_SCORE" ]; then
                # Score increased by more than 10%
                DIFF=$(echo "$CURRENT_SCORE - $BASELINE_SCORE" | bc -l 2>/dev/null || echo "0")
                if [ "$(echo "$DIFF > 0.1" | bc -l 2>/dev/null || echo "0")" -eq 1 ]; then
                  WORSENED=$((WORSENED + 1))
                fi
              fi
            done < current-files.txt
          fi

          echo "new_hotspots=$NEW_HOTSPOTS" >> $GITHUB_OUTPUT
          echo "worsened=$WORSENED" >> $GITHUB_OUTPUT

      - name: Generate Report
        run: |
          cat > hotspot-report.md << 'HEADER'
          ## Hotspot Analysis

          HEADER

          TOP_COUNT=$(jq -r '.hotspots | length' current-hotspots.json)
          echo "**Total hotspots tracked:** $TOP_COUNT" >> hotspot-report.md
          echo "" >> hotspot-report.md

          NEW=${{ steps.compare.outputs.new_hotspots }}
          WORSE=${{ steps.compare.outputs.worsened }}

          if [ "$NEW" -gt 0 ] || [ "$WORSE" -gt 0 ]; then
            echo "### Changes Since Last Analysis" >> hotspot-report.md
            echo "" >> hotspot-report.md
            if [ "$NEW" -gt 0 ]; then
              echo "- **New hotspots:** $NEW" >> hotspot-report.md
            fi
            if [ "$WORSE" -gt 0 ]; then
              echo "- **Worsened files:** $WORSE" >> hotspot-report.md
            fi
            echo "" >> hotspot-report.md
          fi

          echo "### Top 10 Hotspots" >> hotspot-report.md
          echo "" >> hotspot-report.md
          echo "| File | Churn | Complexity | Score |" >> hotspot-report.md
          echo "|------|-------|------------|-------|" >> hotspot-report.md

          jq -r '.hotspots[:10][] | "| `\(.filePath)` | \(.metrics.churnCount // "N/A") | \(.metrics.complexity // "N/A") | \(.ranking.score | tostring[:4]) |"' current-hotspots.json >> hotspot-report.md

          echo "" >> hotspot-report.md
          echo "### Risk Assessment" >> hotspot-report.md
          echo "" >> hotspot-report.md

          # High-risk files (score > 0.8)
          HIGH_RISK=$(jq -r '[.hotspots[] | select(.ranking.score > 0.8)] | length' current-hotspots.json)
          MEDIUM_RISK=$(jq -r '[.hotspots[] | select(.ranking.score > 0.5 and .ranking.score <= 0.8)] | length' current-hotspots.json)

          echo "- **High risk (>0.8):** $HIGH_RISK files" >> hotspot-report.md
          echo "- **Medium risk (0.5-0.8):** $MEDIUM_RISK files" >> hotspot-report.md
          echo "" >> hotspot-report.md

          if [ "$HIGH_RISK" -gt 5 ]; then
            echo "> **Warning:** High number of high-risk hotspots. Consider dedicated refactoring effort." >> hotspot-report.md
          fi

          echo "" >> hotspot-report.md
          echo "---" >> hotspot-report.md
          echo "*Generated by CKB hotspot analysis*" >> hotspot-report.md

      - name: Post PR Comment
        if: github.event_name == 'pull_request'
        run: |
          # Check if PR touches any hotspots
          git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.sha }} > changed-files.txt

          TOUCHED_HOTSPOTS=""
          while IFS= read -r file; do
            SCORE=$(jq -r --arg f "$file" '.hotspots[] | select(.filePath == $f) | .ranking.score // empty' current-hotspots.json)
            if [ -n "$SCORE" ]; then
              TOUCHED_HOTSPOTS="$TOUCHED_HOTSPOTS\n- \`$file\` (score: $SCORE)"
            fi
          done < changed-files.txt

          if [ -n "$TOUCHED_HOTSPOTS" ]; then
            echo "### Hotspot Warning" > pr-comment.md
            echo "" >> pr-comment.md
            echo "This PR modifies the following hotspot files:" >> pr-comment.md
            echo -e "$TOUCHED_HOTSPOTS" >> pr-comment.md
            echo "" >> pr-comment.md
            echo "Extra review recommended for changes to high-churn files." >> pr-comment.md
          fi

      - name: Post PR Hotspot Warning
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        continue-on-error: true
        with:
          header: hotspot-warning
          path: pr-comment.md

      - name: Save Baseline
        uses: actions/upload-artifact@v4
        with:
          name: hotspot-baseline
          path: |
            current-hotspots.json
          retention-days: 90

      - name: Upload Full Report
        uses: actions/upload-artifact@v4
        with:
          name: hotspot-report
          path: |
            current-hotspots.json
            audit-results.json
            hotspot-report.md
          retention-days: 30

  alert-degradation:
    name: Alert on Degradation
    needs: analyze-hotspots
    if: github.event_name == 'schedule' && (needs.analyze-hotspots.outputs.new_hotspots > 3 || needs.analyze-hotspots.outputs.worsened > 2)
    runs-on: ubuntu-latest
    steps:
      - name: Create Alert Issue
        uses: actions/github-script@v7
        with:
          script: |
            const newHotspots = parseInt('${{ needs.analyze-hotspots.outputs.new_hotspots }}');
            const worsened = parseInt('${{ needs.analyze-hotspots.outputs.worsened }}');

            const title = `[CKB] Hotspot Alert: ${newHotspots} new, ${worsened} worsened`;
            const body = `## Hotspot Degradation Detected

            The daily hotspot analysis found concerning trends:

            - **New hotspots:** ${newHotspots}
            - **Worsened files:** ${worsened}

            ### Recommended Actions

            1. Review the [hotspot report artifact](../../actions) for details
            2. Consider scheduling refactoring for high-risk files
            3. Add extra review requirements for hotspot changes

            ---
            *This is an automated alert from CKB hotspot monitoring.*
            `;

            // Check for existing open alert
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['hotspot-alert', 'automated'],
              state: 'open'
            });

            if (issues.data.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['hotspot-alert', 'automated', 'tech-debt']
              });
            }

      - name: Summary
        run: |
          echo "## Hotspot Alert Created" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Significant hotspot degradation detected." >> $GITHUB_STEP_SUMMARY
          echo "- New hotspots: ${{ needs.analyze-hotspots.outputs.new_hotspots }}" >> $GITHUB_STEP_SUMMARY
          echo "- Worsened: ${{ needs.analyze-hotspots.outputs.worsened }}" >> $GITHUB_STEP_SUMMARY
