# CKB PR Analysis Workflow
# This workflow runs CKB analysis on pull requests to provide
# insights about changed code, hotspots, and suggested reviewers.

name: CKB PR Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history needed for git-blame analysis

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install CKB
        run: |
          go install github.com/yourorg/ckb@latest
          # Or download pre-built binary:
          # curl -sSL https://github.com/yourorg/ckb/releases/latest/download/ckb-linux-amd64 -o /usr/local/bin/ckb
          # chmod +x /usr/local/bin/ckb

      - name: Initialize CKB
        run: |
          ckb init
          ckb doctor --fix

      - name: Run PR Summary
        id: pr-summary
        run: |
          # Get PR summary comparing base branch to HEAD
          SUMMARY=$(ckb mcp --json '{
            "tool": "summarizePr",
            "params": {
              "baseBranch": "${{ github.base_ref }}",
              "headBranch": "HEAD"
            }
          }')

          # Extract key metrics
          TOTAL_FILES=$(echo "$SUMMARY" | jq -r '.summary.totalFiles')
          RISK_LEVEL=$(echo "$SUMMARY" | jq -r '.riskAssessment.level')
          HOTSPOTS=$(echo "$SUMMARY" | jq -r '.summary.hotspotsTouched')

          echo "total_files=$TOTAL_FILES" >> $GITHUB_OUTPUT
          echo "risk_level=$RISK_LEVEL" >> $GITHUB_OUTPUT
          echo "hotspots=$HOTSPOTS" >> $GITHUB_OUTPUT
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check Ownership Drift
        id: drift
        run: |
          # Check if PR touches files with ownership drift
          DRIFT=$(ckb mcp --json '{
            "tool": "getOwnershipDrift",
            "params": {
              "threshold": 0.5,
              "limit": 5
            }
          }')

          DRIFT_COUNT=$(echo "$DRIFT" | jq -r '.summary.filesWithDrift')
          echo "drift_count=$DRIFT_COUNT" >> $GITHUB_OUTPUT

      - name: Post PR Comment
        uses: actions/github-script@v7
        with:
          script: |
            const summary = JSON.parse(`${{ steps.pr-summary.outputs.summary }}`);
            const driftCount = ${{ steps.drift.outputs.drift_count }};

            let riskEmoji = '🟢';
            if (summary.riskAssessment.level === 'medium') riskEmoji = '🟡';
            if (summary.riskAssessment.level === 'high') riskEmoji = '🔴';

            let body = `## CKB PR Analysis ${riskEmoji}\n\n`;
            body += `### Summary\n`;
            body += `- **Files Changed:** ${summary.summary.totalFiles}\n`;
            body += `- **Lines Changed:** +${summary.summary.totalAdditions} / -${summary.summary.totalDeletions}\n`;
            body += `- **Modules Affected:** ${summary.summary.totalModules}\n`;
            body += `- **Hotspots Touched:** ${summary.summary.hotspotsTouched}\n`;
            body += `- **Risk Level:** ${summary.riskAssessment.level}\n\n`;

            if (summary.riskAssessment.factors.length > 0) {
              body += `### Risk Factors\n`;
              summary.riskAssessment.factors.forEach(f => {
                body += `- ${f}\n`;
              });
              body += `\n`;
            }

            if (summary.riskAssessment.suggestions.length > 0) {
              body += `### Suggestions\n`;
              summary.riskAssessment.suggestions.forEach(s => {
                body += `- ${s}\n`;
              });
              body += `\n`;
            }

            if (summary.suggestedReviewers && summary.suggestedReviewers.length > 0) {
              body += `### Suggested Reviewers\n`;
              summary.suggestedReviewers.slice(0, 3).forEach(r => {
                body += `- **${r.owner}** - ${r.reason}\n`;
              });
              body += `\n`;
            }

            if (driftCount > 0) {
              body += `### ⚠️ Ownership Drift Detected\n`;
              body += `${driftCount} file(s) in this PR have significant ownership drift. `;
              body += `Consider updating CODEOWNERS.\n`;
            }

            body += `\n---\n*Generated by CKB*`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });

      - name: Fail on High Risk
        if: steps.pr-summary.outputs.risk_level == 'high'
        run: |
          echo "::warning::This PR has been flagged as HIGH RISK"
          echo "Please ensure thorough review before merging."
          # Optionally fail the workflow:
          # exit 1
