# Reusable CKB Analysis Workflow
# Standardized analysis for organization-wide use
#
# Usage in your workflow:
#
# jobs:
#   analyze:
#     uses: your-org/.github/.github/workflows/reusable-analysis.yml@main
#     with:
#       risk_threshold: 'high'
#       enable_complexity: true
#     secrets:
#       token: ${{ secrets.GITHUB_TOKEN }}

name: Reusable CKB Analysis

on:
  workflow_call:
    inputs:
      risk_threshold:
        description: 'Risk level to fail on (low, medium, high, critical)'
        required: false
        type: string
        default: 'critical'
      enable_complexity:
        description: 'Enable complexity checking'
        required: false
        type: boolean
        default: true
      enable_ownership:
        description: 'Enable ownership drift detection'
        required: false
        type: boolean
        default: true
      enable_reviewers:
        description: 'Auto-request reviewers'
        required: false
        type: boolean
        default: true
      max_cyclomatic:
        description: 'Maximum cyclomatic complexity'
        required: false
        type: number
        default: 15
      max_cognitive:
        description: 'Maximum cognitive complexity'
        required: false
        type: number
        default: 20
      ckb_version:
        description: 'CKB version to install'
        required: false
        type: string
        default: 'latest'
    secrets:
      token:
        description: 'GitHub token for API calls'
        required: true
    outputs:
      risk_level:
        description: 'Detected risk level'
        value: ${{ jobs.analyze.outputs.risk }}
      files_changed:
        description: 'Number of files changed'
        value: ${{ jobs.analyze.outputs.files }}
      complexity_violations:
        description: 'Number of complexity violations'
        value: ${{ jobs.analyze.outputs.complexity_violations }}

jobs:
  analyze:
    name: CKB Analysis
    runs-on: ubuntu-latest
    outputs:
      risk: ${{ steps.impact.outputs.risk }}
      files: ${{ steps.impact.outputs.files }}
      complexity_violations: ${{ steps.complexity.outputs.violations }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CKB
        run: |
          if [ "${{ inputs.ckb_version }}" = "latest" ]; then
            npm install -g @tastehub/ckb
          else
            npm install -g @tastehub/ckb@${{ inputs.ckb_version }}
          fi

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: .ckb/
          key: ckb-${{ runner.os }}-${{ hashFiles('**/*.go', '**/*.ts', '**/*.py', '**/*.rs', '**/*.java') }}
          restore-keys: |
            ckb-${{ runner.os }}-

      - name: Initialize
        run: |
          ckb init
          ckb index --if-stale=24h

      - name: Impact Analysis
        id: impact
        run: |
          RANGE="${{ github.event.pull_request.base.sha }}..${{ github.sha }}"

          ckb impact --range="$RANGE" --format=json > impact.json

          RISK=$(jq -r '.summary.estimatedRisk // "low"' impact.json)
          FILES=$(jq -r '.summary.filesChanged // 0' impact.json)
          AFFECTED=$(jq -r '.summary.transitivelyAffected // 0' impact.json)

          echo "risk=$RISK" >> $GITHUB_OUTPUT
          echo "files=$FILES" >> $GITHUB_OUTPUT
          echo "affected=$AFFECTED" >> $GITHUB_OUTPUT

          # Generate markdown report
          ckb impact --range="$RANGE" --format=markdown > impact.md

      - name: Complexity Check
        if: inputs.enable_complexity
        id: complexity
        run: |
          VIOLATIONS=0

          git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.sha }} \
            | grep -E '\.(go|ts|tsx|js|jsx|py|rs|java)$' > changed-files.txt || true

          while IFS= read -r file; do
            if [ -f "$file" ]; then
              RESULT=$(ckb complexity "$file" --format=json 2>/dev/null || echo '{}')
              CYCLO=$(echo "$RESULT" | jq -r '.metrics.cyclomaticComplexity // 0')
              COGNITIVE=$(echo "$RESULT" | jq -r '.metrics.cognitiveComplexity // 0')

              if [ "$CYCLO" -gt "${{ inputs.max_cyclomatic }}" ] || [ "$COGNITIVE" -gt "${{ inputs.max_cognitive }}" ]; then
                VIOLATIONS=$((VIOLATIONS + 1))
              fi
            fi
          done < changed-files.txt

          echo "violations=$VIOLATIONS" >> $GITHUB_OUTPUT

      - name: Ownership Analysis
        if: inputs.enable_ownership
        run: |
          ckb ownership drift --threshold=0.5 --format=json > drift.json

          DRIFT_COUNT=$(jq -r '.summary.filesWithDrift // 0' drift.json)

          if [ "$DRIFT_COUNT" -gt 0 ]; then
            echo "" >> impact.md
            echo "### Ownership Drift" >> impact.md
            echo "" >> impact.md
            echo "**$DRIFT_COUNT** file(s) have ownership drift. Consider updating CODEOWNERS." >> impact.md
          fi

      - name: Get Reviewers
        if: inputs.enable_reviewers
        id: reviewers
        run: |
          RANGE="${{ github.event.pull_request.base.sha }}..${{ github.sha }}"
          REVIEWERS=$(ckb reviewers --range="$RANGE" --format=gh 2>/dev/null || echo "")
          echo "list=$REVIEWERS" >> $GITHUB_OUTPUT

      - name: Post Analysis Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ckb-analysis
          path: impact.md

      - name: Request Reviewers
        if: inputs.enable_reviewers && steps.reviewers.outputs.list != ''
        run: |
          gh pr edit ${{ github.event.pull_request.number }} \
            --add-reviewer "${{ steps.reviewers.outputs.list }}"
        env:
          GH_TOKEN: ${{ secrets.token }}

      - name: Save Cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .ckb/
          key: ckb-${{ runner.os }}-${{ hashFiles('**/*.go', '**/*.ts', '**/*.py', '**/*.rs', '**/*.java') }}

      - name: Risk Gate
        run: |
          RISK="${{ steps.impact.outputs.risk }}"
          THRESHOLD="${{ inputs.risk_threshold }}"

          # Map risk levels to numbers for comparison
          risk_to_num() {
            case "$1" in
              low) echo 1 ;;
              medium) echo 2 ;;
              high) echo 3 ;;
              critical) echo 4 ;;
              *) echo 0 ;;
            esac
          }

          RISK_NUM=$(risk_to_num "$RISK")
          THRESHOLD_NUM=$(risk_to_num "$THRESHOLD")

          if [ "$RISK_NUM" -ge "$THRESHOLD_NUM" ]; then
            echo "::error::Risk level '$RISK' meets or exceeds threshold '$THRESHOLD'"
            exit 1
          fi

      - name: Complexity Gate
        if: inputs.enable_complexity && steps.complexity.outputs.violations > 0
        run: |
          echo "::error::${{ steps.complexity.outputs.violations }} file(s) exceed complexity thresholds"
          exit 1

      - name: Summary
        if: always()
        run: |
          echo "## CKB Analysis Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Risk Level | ${{ steps.impact.outputs.risk }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Files Changed | ${{ steps.impact.outputs.files }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Transitively Affected | ${{ steps.impact.outputs.affected }} |" >> $GITHUB_STEP_SUMMARY
          if [ "${{ inputs.enable_complexity }}" = "true" ]; then
            echo "| Complexity Violations | ${{ steps.complexity.outputs.violations }} |" >> $GITHUB_STEP_SUMMARY
          fi
