# Risk Audit Workflow
# Comprehensive codebase risk analysis using 8 weighted factors
# Identifies critical areas and suggests quick wins
#
# Usage: Copy to .github/workflows/risk-audit.yml

name: Risk Audit

on:
  schedule:
    # Run weekly on Mondays at 6 AM UTC
    - cron: '0 6 * * 1'
  workflow_dispatch:
    inputs:
      min_score:
        description: 'Minimum risk score to report (0-100)'
        required: false
        default: '60'
      fail_on_critical:
        description: 'Fail if critical risks found'
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  issues: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CKB
        run: npm install -g @tastehub/ckb

      - name: Initialize
        run: |
          ckb init
          ckb index

      - name: Run Risk Audit
        id: audit
        run: |
          MIN_SCORE="${{ github.event.inputs.min_score || '60' }}"

          ckb audit --min-score="$MIN_SCORE" --limit=50 --format=json > audit.json

          CRITICAL=$(jq -r '.summary.critical // 0' audit.json)
          HIGH=$(jq -r '.summary.high // 0' audit.json)
          MEDIUM=$(jq -r '.summary.medium // 0' audit.json)

          echo "critical=$CRITICAL" >> $GITHUB_OUTPUT
          echo "high=$HIGH" >> $GITHUB_OUTPUT
          echo "medium=$MEDIUM" >> $GITHUB_OUTPUT

      - name: Generate Report
        run: |
          cat > audit-report.md << 'EOF'
          # Risk Audit Report

          **Generated:** $(date -u +%Y-%m-%d)
          **Minimum Score:** ${{ github.event.inputs.min_score || '60' }}

          ## Summary

          | Risk Level | Count |
          |------------|-------|
          EOF

          CRITICAL=${{ steps.audit.outputs.critical }}
          HIGH=${{ steps.audit.outputs.high }}
          MEDIUM=${{ steps.audit.outputs.medium }}

          echo "| 🔴 Critical | $CRITICAL |" >> audit-report.md
          echo "| 🟠 High | $HIGH |" >> audit-report.md
          echo "| 🟡 Medium | $MEDIUM |" >> audit-report.md

          echo "" >> audit-report.md
          echo "## Risk Factors" >> audit-report.md
          echo "" >> audit-report.md
          echo "| Factor | Weight | Description |" >> audit-report.md
          echo "|--------|--------|-------------|" >> audit-report.md
          echo "| Complexity | 20% | Cyclomatic/cognitive complexity |" >> audit-report.md
          echo "| Test Coverage | 20% | Percentage covered by tests |" >> audit-report.md
          echo "| Bus Factor | 15% | Single-author code is risky |" >> audit-report.md
          echo "| Security Sensitive | 15% | Auth/crypto/credential code |" >> audit-report.md
          echo "| Staleness | 10% | Time since last modification |" >> audit-report.md
          echo "| Error Rate | 10% | Runtime errors from telemetry |" >> audit-report.md
          echo "| Coupling | 5% | Tightly coupled files |" >> audit-report.md
          echo "| Churn | 5% | Frequency of changes |" >> audit-report.md

          echo "" >> audit-report.md
          echo "## Critical Risk Files" >> audit-report.md
          echo "" >> audit-report.md

          if [ "$CRITICAL" -gt 0 ]; then
            echo "| File | Score | Top Factors |" >> audit-report.md
            echo "|------|-------|-------------|" >> audit-report.md
            jq -r '.items[] | select(.riskLevel == "critical") | "| `\(.file)` | \(.riskScore) | \(.factors[:2] | map(.factor) | join(", ")) |"' audit.json >> audit-report.md
          else
            echo "*No critical risk files found.*" >> audit-report.md
          fi

          echo "" >> audit-report.md
          echo "## High Risk Files" >> audit-report.md
          echo "" >> audit-report.md

          if [ "$HIGH" -gt 0 ]; then
            echo "| File | Score | Top Factors |" >> audit-report.md
            echo "|------|-------|-------------|" >> audit-report.md
            jq -r '.items[] | select(.riskLevel == "high") | "| `\(.file)` | \(.riskScore) | \(.factors[:2] | map(.factor) | join(", ")) |"' audit.json | head -20 >> audit-report.md
          else
            echo "*No high risk files found.*" >> audit-report.md
          fi

          echo "" >> audit-report.md
          echo "## Quick Wins" >> audit-report.md
          echo "" >> audit-report.md

          QUICK_WINS=$(jq -r '.quickWins | length // 0' audit.json)
          if [ "$QUICK_WINS" -gt 0 ]; then
            echo "Low-effort, high-impact improvements:" >> audit-report.md
            echo "" >> audit-report.md
            jq -r '.quickWins[] | "- **\(.action)**: `\(.target)` (effort: \(.effort), impact: \(.impact))"' audit.json >> audit-report.md
          else
            echo "*No quick wins identified.*" >> audit-report.md
          fi

          echo "" >> audit-report.md
          echo "---" >> audit-report.md
          echo "*Generated by CKB risk audit*" >> audit-report.md

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: risk-audit-report
          path: |
            audit.json
            audit-report.md
          retention-days: 90

      - name: Create/Update Issue
        if: steps.audit.outputs.critical > 0 || steps.audit.outputs.high > 5
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('audit-report.md', 'utf8');
            const critical = parseInt('${{ steps.audit.outputs.critical }}');
            const high = parseInt('${{ steps.audit.outputs.high }}');

            const title = `[CKB] Risk Audit: ${critical} critical, ${high} high-risk files`;

            // Check for existing open issue
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['risk-audit', 'automated'],
              state: 'open'
            });

            if (issues.data.length > 0) {
              // Update existing issue
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issues.data[0].number,
                title: title,
                body: report
              });
            } else {
              // Create new issue
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: report,
                labels: ['risk-audit', 'automated', 'tech-debt']
              });
            }

      - name: Summary
        run: |
          echo "## Risk Audit Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Level | Count |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Critical | ${{ steps.audit.outputs.critical }} |" >> $GITHUB_STEP_SUMMARY
          echo "| High | ${{ steps.audit.outputs.high }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Medium | ${{ steps.audit.outputs.medium }} |" >> $GITHUB_STEP_SUMMARY

      - name: Fail on Critical
        if: github.event.inputs.fail_on_critical == 'true' && steps.audit.outputs.critical > 0
        run: |
          echo "::error::Found ${{ steps.audit.outputs.critical }} critical risk files"
          exit 1
