# Slack Notifications Workflow
# Sends CKB analysis results to Slack
#
# Prerequisites:
#   1. Create a Slack app at https://api.slack.com/apps
#   2. Add Incoming Webhooks to your app
#   3. Add webhook URL as SLACK_WEBHOOK_URL secret
#
# Usage: Copy to .github/workflows/slack-notifications.yml

name: Slack Notifications

on:
  pull_request:
    types: [opened, synchronize]
  schedule:
    # Daily summary at 9 AM UTC
    - cron: '0 9 * * 1-5'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  pr-notification:
    name: PR Analysis Notification
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CKB
        run: npm install -g @tastehub/ckb

      - name: Analyze PR
        id: analyze
        run: |
          ckb init
          ckb index --if-stale=24h

          RANGE="${{ github.event.pull_request.base.sha }}..${{ github.sha }}"
          ckb impact --range="$RANGE" --format=json > impact.json

          RISK=$(jq -r '.summary.estimatedRisk // "low"' impact.json)
          FILES=$(jq -r '.summary.filesChanged // 0' impact.json)
          AFFECTED=$(jq -r '.summary.transitivelyAffected // 0' impact.json)
          HOTSPOTS=$(jq -r '.summary.hotspotsTouched // 0' impact.json)

          echo "risk=$RISK" >> $GITHUB_OUTPUT
          echo "files=$FILES" >> $GITHUB_OUTPUT
          echo "affected=$AFFECTED" >> $GITHUB_OUTPUT
          echo "hotspots=$HOTSPOTS" >> $GITHUB_OUTPUT

      - name: Send High-Risk Alert
        if: steps.analyze.outputs.risk == 'high' || steps.analyze.outputs.risk == 'critical'
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "${{ steps.analyze.outputs.risk == 'critical' && '🚨' || '⚠️' }} High-Risk PR Detected",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Risk Level:*\n${{ steps.analyze.outputs.risk }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Files Changed:*\n${{ steps.analyze.outputs.files }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Transitively Affected:*\n${{ steps.analyze.outputs.affected }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*PR:* <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}>"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Author:* ${{ github.event.pull_request.user.login }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Generated by CKB analysis"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  daily-summary:
    name: Daily Summary
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CKB
        run: npm install -g @tastehub/ckb

      - name: Generate Summary
        id: summary
        run: |
          ckb init
          ckb index

          # Get hotspots
          ckb hotspots --limit=10 --format=json > hotspots.json
          HOTSPOT_COUNT=$(jq -r '.hotspots | length' hotspots.json)
          HIGH_RISK=$(jq -r '[.hotspots[] | select(.ranking.score > 0.8)] | length' hotspots.json)

          # Get dead code
          ckb dead-code --threshold=0.9 --limit=10 --format=json > dead-code.json
          DEAD_CODE=$(jq -r '.candidates | length' dead-code.json)

          # Get ownership drift
          ckb ownership drift --threshold=0.5 --format=json > drift.json
          DRIFT_COUNT=$(jq -r '.summary.filesWithDrift // 0' drift.json)

          echo "hotspots=$HOTSPOT_COUNT" >> $GITHUB_OUTPUT
          echo "high_risk=$HIGH_RISK" >> $GITHUB_OUTPUT
          echo "dead_code=$DEAD_CODE" >> $GITHUB_OUTPUT
          echo "drift=$DRIFT_COUNT" >> $GITHUB_OUTPUT

          # Get top hotspots for message
          TOP_HOTSPOTS=$(jq -r '.hotspots[:3][] | "• `\(.filePath)` (score: \(.ranking.score | tostring[:4]))"' hotspots.json | tr '\n' '\\n')
          echo "top_hotspots<<EOF" >> $GITHUB_OUTPUT
          echo "$TOP_HOTSPOTS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Daily Summary
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "📊 Daily Code Health Summary",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Repository:* ${{ github.repository }}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*🔥 Hotspots:*\n${{ steps.summary.outputs.hotspots }} total (${{ steps.summary.outputs.high_risk }} high-risk)"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*🗑️ Dead Code:*\n${{ steps.summary.outputs.dead_code }} candidates"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*👥 Ownership Drift:*\n${{ steps.summary.outputs.drift }} files"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Top Hotspots:*\n${{ steps.summary.outputs.top_hotspots }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Generated by CKB • <${{ github.server_url }}/${{ github.repository }}/actions|View Details>"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  # Alternative: Discord notifications
  # Uncomment and set DISCORD_WEBHOOK_URL secret
  # discord-notification:
  #   name: Discord Notification
  #   if: github.event_name == 'pull_request'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #
  #     - name: Setup and Analyze
  #       id: analyze
  #       run: |
  #         npm install -g @tastehub/ckb
  #         ckb init && ckb index --if-stale=24h
  #         ckb impact --range="${{ github.event.pull_request.base.sha }}..${{ github.sha }}" --format=json > impact.json
  #         echo "risk=$(jq -r '.summary.estimatedRisk' impact.json)" >> $GITHUB_OUTPUT
  #
  #     - name: Send Discord Alert
  #       if: steps.analyze.outputs.risk == 'high' || steps.analyze.outputs.risk == 'critical'
  #       run: |
  #         curl -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" \
  #           -H "Content-Type: application/json" \
  #           -d '{
  #             "embeds": [{
  #               "title": "⚠️ High-Risk PR Detected",
  #               "description": "PR #${{ github.event.pull_request.number }} has been flagged as ${{ steps.analyze.outputs.risk }} risk.",
  #               "url": "${{ github.event.pull_request.html_url }}",
  #               "color": 15158332,
  #               "fields": [
  #                 {"name": "Repository", "value": "${{ github.repository }}", "inline": true},
  #                 {"name": "Author", "value": "${{ github.event.pull_request.user.login }}", "inline": true}
  #               ]
  #             }]
  #           }'
