# Telemetry-Enriched Dead Code Detection
# Combines static analysis with production telemetry for high-confidence dead code detection
#
# Usage: Copy to .github/workflows/telemetry-dead-code.yml
#
# Prerequisites:
#   - Telemetry collection enabled (see Telemetry.md)
#   - Telemetry data available at configured endpoint

name: Telemetry Dead Code

on:
  schedule:
    # Run weekly for telemetry-based analysis
    - cron: '0 4 * * 1'
  workflow_dispatch:
    inputs:
      static_threshold:
        description: 'Static analysis confidence threshold'
        required: false
        default: '0.9'
      telemetry_days:
        description: 'Days of telemetry data to analyze'
        required: false
        default: '30'
      include_static:
        description: 'Include static-only analysis'
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  issues: write

env:
  STATIC_THRESHOLD: 0.9
  TELEMETRY_DAYS: 30

jobs:
  analyze:
    name: Analyze Dead Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CKB
        run: npm install -g @tastehub/ckb

      - name: Initialize
        run: |
          ckb init
          ckb index

      - name: Static Dead Code Analysis
        id: static
        run: |
          THRESHOLD="${{ github.event.inputs.static_threshold || env.STATIC_THRESHOLD }}"

          ckb dead-code \
            --threshold="$THRESHOLD" \
            --limit=100 \
            --format=json \
            > static-dead-code.json

          STATIC_COUNT=$(jq '.candidates | length // 0' static-dead-code.json)
          echo "count=$STATIC_COUNT" >> $GITHUB_OUTPUT

      - name: Telemetry Dead Code Analysis
        id: telemetry
        run: |
          DAYS="${{ github.event.inputs.telemetry_days || env.TELEMETRY_DAYS }}"

          # Check if telemetry is configured
          if ckb telemetry status 2>/dev/null | grep -q "connected"; then
            echo "has_telemetry=true" >> $GITHUB_OUTPUT

            # Get dead code from production telemetry
            ckb dead-code \
              --source=telemetry \
              --days="$DAYS" \
              --limit=100 \
              --format=json \
              > telemetry-dead-code.json

            TELEMETRY_COUNT=$(jq '.candidates | length // 0' telemetry-dead-code.json)
            echo "count=$TELEMETRY_COUNT" >> $GITHUB_OUTPUT

            # Get coverage stats
            COVERED=$(jq '.coverage.coveredSymbols // 0' telemetry-dead-code.json)
            TOTAL=$(jq '.coverage.totalSymbols // 0' telemetry-dead-code.json)
            echo "covered=$COVERED" >> $GITHUB_OUTPUT
            echo "total=$TOTAL" >> $GITHUB_OUTPUT
          else
            echo "has_telemetry=false" >> $GITHUB_OUTPUT
            echo "count=0" >> $GITHUB_OUTPUT
            echo '{"candidates":[],"source":"telemetry","coverage":{}}' > telemetry-dead-code.json
          fi

      - name: Combine Results
        run: |
          # Merge static and telemetry results
          jq -s '
            {
              static: .[0],
              telemetry: .[1],
              combined: (
                [.[0].candidates[]? | . + {source: "static"}] +
                [.[1].candidates[]? | . + {source: "telemetry"}]
                | unique_by(.symbol)
                | sort_by(-.confidence)
              )
            }
          ' static-dead-code.json telemetry-dead-code.json > combined-dead-code.json

          # Count by source and confidence
          STATIC_HIGH=$(jq '[.static.candidates[]? | select(.confidence >= 0.95)] | length' combined-dead-code.json)
          TELEMETRY_HIGH=$(jq '[.telemetry.candidates[]? | select(.confidence >= 0.95)] | length' combined-dead-code.json)
          BOTH=$(jq '
            [.static.candidates[]?.symbol] as $static |
            [.telemetry.candidates[]? | select(.symbol | IN($static[]))] | length
          ' combined-dead-code.json)

          echo "STATIC_HIGH=$STATIC_HIGH" >> $GITHUB_ENV
          echo "TELEMETRY_HIGH=$TELEMETRY_HIGH" >> $GITHUB_ENV
          echo "CONFIRMED_BOTH=$BOTH" >> $GITHUB_ENV

      - name: Generate Report
        run: |
          cat > dead-code-report.md << 'HEADER'
          # Dead Code Analysis Report

          ## Summary

          HEADER

          echo "| Source | Candidates | High Confidence (>95%) |" >> dead-code-report.md
          echo "|--------|------------|------------------------|" >> dead-code-report.md
          echo "| Static Analysis | ${{ steps.static.outputs.count }} | $STATIC_HIGH |" >> dead-code-report.md

          if [ "${{ steps.telemetry.outputs.has_telemetry }}" == "true" ]; then
            echo "| Production Telemetry | ${{ steps.telemetry.outputs.count }} | $TELEMETRY_HIGH |" >> dead-code-report.md
            echo "| **Confirmed by Both** | $CONFIRMED_BOTH | — |" >> dead-code-report.md
          else
            echo "| Production Telemetry | *Not configured* | — |" >> dead-code-report.md
          fi

          echo "" >> dead-code-report.md

          # Telemetry coverage info
          if [ "${{ steps.telemetry.outputs.has_telemetry }}" == "true" ]; then
            COVERED=${{ steps.telemetry.outputs.covered }}
            TOTAL=${{ steps.telemetry.outputs.total }}
            if [ "$TOTAL" -gt 0 ]; then
              PCT=$(echo "scale=1; $COVERED * 100 / $TOTAL" | bc)
              echo "**Telemetry Coverage:** $COVERED / $TOTAL symbols ($PCT%)" >> dead-code-report.md
              echo "" >> dead-code-report.md
            fi
          fi

          # Confirmed dead code (highest confidence)
          if [ "$CONFIRMED_BOTH" -gt 0 ]; then
            echo "## 🔴 Confirmed Dead Code (Both Sources)" >> dead-code-report.md
            echo "" >> dead-code-report.md
            echo "These symbols are unused in both static analysis AND production:" >> dead-code-report.md
            echo "" >> dead-code-report.md
            echo "| Symbol | File | Static Conf. | Last Called |" >> dead-code-report.md
            echo "|--------|------|--------------|-------------|" >> dead-code-report.md

            jq -r '
              [.static.candidates[]?.symbol] as $static |
              .telemetry.candidates[]? |
              select(.symbol | IN($static[])) |
              "| `\(.symbol)` | `\(.file // "—")` | \((.confidence // 0) * 100 | floor)% | \(.lastCalled // "Never") |"
            ' combined-dead-code.json | head -20 >> dead-code-report.md
            echo "" >> dead-code-report.md
          fi

          # Static-only high confidence
          echo "## 🟠 Static Analysis Only (>95% confidence)" >> dead-code-report.md
          echo "" >> dead-code-report.md

          if [ "$STATIC_HIGH" -gt 0 ]; then
            echo "| Symbol | File | Type | Confidence |" >> dead-code-report.md
            echo "|--------|------|------|------------|" >> dead-code-report.md

            jq -r '.static.candidates[]? | select(.confidence >= 0.95) | "| `\(.symbol)` | `\(.file // "—")` | \(.type // "—") | \((.confidence // 0) * 100 | floor)% |"' combined-dead-code.json | head -20 >> dead-code-report.md
          else
            echo "*No high-confidence static dead code found.*" >> dead-code-report.md
          fi

          echo "" >> dead-code-report.md

          # Telemetry dead code
          if [ "${{ steps.telemetry.outputs.has_telemetry }}" == "true" ] && [ "$TELEMETRY_HIGH" -gt 0 ]; then
            echo "## 🟡 Telemetry Dead Code (No production calls)" >> dead-code-report.md
            echo "" >> dead-code-report.md
            echo "| Symbol | File | Last Called | Days Since |" >> dead-code-report.md
            echo "|--------|------|-------------|------------|" >> dead-code-report.md

            jq -r '.telemetry.candidates[]? | select(.confidence >= 0.95) | "| `\(.symbol)` | `\(.file // "—")` | \(.lastCalled // "Never") | \(.daysSinceCall // "∞") |"' combined-dead-code.json | head -20 >> dead-code-report.md
            echo "" >> dead-code-report.md
          fi

          # Recommendations
          echo "## Recommendations" >> dead-code-report.md
          echo "" >> dead-code-report.md

          if [ "$CONFIRMED_BOTH" -gt 0 ]; then
            echo "1. **Immediate cleanup:** Remove $CONFIRMED_BOTH symbol(s) confirmed dead by both sources" >> dead-code-report.md
          fi

          if [ "${{ steps.telemetry.outputs.has_telemetry }}" != "true" ]; then
            echo "1. **Enable telemetry:** Production data significantly improves dead code detection accuracy" >> dead-code-report.md
            echo "   See: [Telemetry Documentation](https://github.com/SimplyLiz/CodeMCPWiki/wiki/Telemetry)" >> dead-code-report.md
          fi

          echo "" >> dead-code-report.md
          echo "---" >> dead-code-report.md
          echo "*Generated by CKB telemetry-enriched dead code analysis*" >> dead-code-report.md

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: dead-code-analysis
          path: |
            static-dead-code.json
            telemetry-dead-code.json
            combined-dead-code.json
            dead-code-report.md
          retention-days: 90

      - name: Create Issue for Confirmed Dead Code
        if: env.CONFIRMED_BOTH > 5
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('dead-code-report.md', 'utf8');
            const confirmed = parseInt('${{ env.CONFIRMED_BOTH }}');

            const title = `[CKB] Dead Code Alert: ${confirmed} symbols confirmed unused`;

            // Check for existing open issue
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['dead-code', 'telemetry', 'automated'],
              state: 'open'
            });

            if (issues.data.length > 0) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issues.data[0].number,
                body: report
              });
            } else {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: report,
                labels: ['dead-code', 'telemetry', 'automated', 'tech-debt']
              });
            }

      - name: Summary
        run: |
          echo "## Dead Code Analysis" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Source | Candidates |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|------------|" >> $GITHUB_STEP_SUMMARY
          echo "| Static | ${{ steps.static.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Telemetry | ${{ steps.telemetry.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Confirmed (Both) | $CONFIRMED_BOTH |" >> $GITHUB_STEP_SUMMARY
