version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - misspell
    - nilerr
    - unconvert
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      disable:
        - fieldalignment
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - std-error-handling
    rules:
      # Exclude v2 style suggestions that weren't enforced in v1
      - linters:
          - staticcheck
        text: "^(QF|ST)"
      - linters:
          - errcheck
        path: _test\.go
        text: os.RemoveAll
      - linters:
          - govet
        path: _test\.go
        text: shadow
      - linters:
          - govet
        path: _test\.go
        text: unusedwrite
      - linters:
          - errcheck
        text: fmt.Sscanf
      - linters:
          - errcheck
        path: cmd/
        text: fmt\.(Fprintf|Fprintln|Fprint)
      - linters:
          - errcheck
        path: cmd/
        text: Flush
      - linters:
          - errcheck
        text: Body\.Close
      - linters:
          - errcheck
        path: cmd/
        text: MarkFlagRequired
      - linters:
          - errcheck
        path: cmd/
        text: fmt\.Scanln
      - linters:
          - errcheck
        path: cmd/ckb/daemon\.go
        text: Seek
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - ckb
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
