version: 2

project_name: ckb

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: ckb
    main: ./cmd/ckb
    binary: ckb
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X ckb/internal/version.Version={{.Version}}
      - -X ckb/internal/version.Commit={{.ShortCommit}}
      - -X ckb/internal/version.BuildDate={{.Date}}
    # Ignore non-existent directories that might appear in go:generate
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))?\!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\(.+\))?\!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\(.+\))?\!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: simplyliz
    name: ckb
  prerelease: auto
  draft: false
  name_template: "CKB v{{.Version}}"
