coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 2%
    patch:
      default:
        target: 50%

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: true
