coverage:
  status:
    project:
      default:
        target: 30%
        threshold: 0%
    patch:
      default:
        target: 80%
        threshold: 0%

comment:
  layout: "header, diff, flags, components, files"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true
  hide_project_coverage: false

github_checks:
  annotations: true
